language: scala

scala:
  - 2.12.3
  - 2.11.11

sudo: false
script:
  - sbt ++$TRAVIS_SCALA_VERSION 'testOnly IndexingSpecMaterialized'
  - sbt ++$TRAVIS_SCALA_VERSION 'testOnly IndexingSpecNonMaterialized'
#  - $TRAVIS_BUILD_DIR/travis/script/build.sh

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
  - $HOME/.sbt

git:
  submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

env:
  global:
  - secure: wML88eATztut1NMEBF2Er3832bXc8knACwn2ZHWpEasVmxuyrG5ZCKcx7SYyiLRmJDTDiedYGGNsZ/SEz5THkjGV+g4Mnux6DFJ+5P6h+EopgPsFfxFe3oOUeqT8rrCzjAL579OaUKVNqLnIjdeNt6i+vE4G2m3/sj7/HDASMzaqB1le38HXon7t348zIaXAZ5/pdqkJpziT4bK1JLPAvs+U+rT/+BVMhrBqyT+CxYWz9I0W+W3U9oS1lIjs/IRXZQ3j0HtNp3AfyDx3Co4j8J0wUDc1Qcw6O1nqcjkmI1d8UYUnLzNzlewydGjh9LQ75m2bmdbDwlTN9kQ377HppGDhXPsXnMTCk5zNX365aYn6tDoIYd76tItbDxVXz5YxwedizEqK7NBTa8apVnitwKhsqyyiYLQCYAUdme9af4Qel7NyOpIQKTwrLBqMevuUf+C9XfVLuGMMSq+pTSEuS+O8/Oca7lVq8LsuTHyPtyU3GpLkPLhnhe/cWz7rtKiXnGANs0Mx9y1y+9MrswFNlZRF98BPXLl94yilXMqz0pZ9GL0rRAwzxFhUEUZQF7mEvUwcVI21n6AD8aiyFZTLWVyW6Q0cRcEewJ2Ps490SjopM/evVpAL78Bw5yOgsmsb+/BdC1L9PLN9VWEK7jGfIFPv9f2eoNZLxu1YaWJGAI8=
  - secure: VF7z1jOa8kh1oUxiAGhWdWDm3D7EZKwuLW0yd2mTpWSOzOdb6dEJseotvnBE74RDBCsZAm0l5lxszvKyYa+zkfgkGYLPWDUj6bqtCyNuVywpQ9yl9HeKRibh1ozNT36Po8Dl52iPPz75BG3gyaaer4qGXn3h8q4C7tNs1FvvtPPASHGjqahGfispamvkGJBQhkuISmPfnYmQUA5IzaEm2fsHyb8jR78fggTS6d5vQll2bckjK6+WKWg5caizKRhG42TNC0s0gx1tWLnB0xJy9W8XnDGSYmXw8gsh6WPmMbIdvjmMuO3OD/tUp42T/O+qDQNcmy6FM/aO1hp5dLVDN2AAopaSZVkMEsOm9sICs7ishjtPGX7ztrMNNyQZwqi/zVKsd6/09taDTVWXWxnedxfxJHBNOKz4yFs/jYwNqN5EFsZEKS8MUbxVwTbySIY83nn3jDrT3toOiRMsJfkQ598lp5BV/fzBfJ2PYgvJ6YmSOyAWle/Ky9nkLVpGXMwI0rHRB1UK4SIZExAaDay5uCMSZ7Agg0fHo47iV392DkkzaSX6QvyIN67iEBiRhjj1cCdThZPIfAJ1fCa/itioVjVrIU9jJJ2oCEaYYVRY8h1xTiWy8UIIchrqIS03CPsJgtTPZnqRfF8YBSA0OzPHSr9pdcDWC5XC4pE9tOpnWrE=
  - secure: qBxyO+/vt0a3LSuHziWo43xHQccmaH8gVn5cd3JHa8MxMWxYBNtW8Z7/t1TtODNx/elerEK6NszGkK6YyV6wvA/sgCObucBtQ3GS9mRHqF6eiN1yhpu17JFaTVdWvgqQK+s5+hQMkXJAg5eMLoAqmJalgBVKG9gTS5J6tQmz1uvN13czxG4EPD0dAErFdRrDyb0QlHYiwaEgauK/05lf5/zxrLGaMRKZF8Qju4ICbL9P5PFeuUzunwUMikgvLARuah8hiOjpwF1P8Crut3NkX2UynKNA4U8abLFvj/Dzt1AT+j19H5wgBFggbLuoZwnncq0/GOcQ0jJaaY5l9ITanG1+4omJa3dMAOZMl7GNDY3qry7HrAauziYgzXqebxSyG7SpbRTBDcUGJT9aD/T2hqSgTOE/zbitMWHDlqza+k5T/+xxDjk4PtgEE1Z3BWjJZ5J/YyzJFQw9xt139XUNKCu1wQIvIDa6pQjLmEPidqyI4+KacLmHjRf3WZ+62z0qmZ3Qy5cgzxVwM63Z/vInZnGsEEr/cVcffltnU17BYyJRMddCBE/uFmNeya7vJFJbLExUFjQx2X6dgtLVycnzNo8VzwIePig3Zd5Ff5xuUsncGf27OsTs/KC3HRQifqp8jGUdKt+MEqmuC+w+qLOtbjdNyxe0S609hfxu3EdJya4=
  - secure: z23lVyu0CKpX4UChnCVP3NnakxVOn3ZAvCP0Vs2lHlsljeRF1+C8J/atBunlyLz5d0TdAd1CWRh5DUmb2ho2rNsva41qWwodMTIR06M4MZguT0SL2i10bsYHLQExnJ4ri0sSh44GU0+ovNBbq5WibYWUccRzjAG17zb77xIfKXeKL6w4a0ieiq5e0VKqQlXIaFwVNsyV3Ln/LSg1vl4pNwBDnHXm79gHoOHTkgtd38/1hBVx6lo8WIyXefRIFo5b2xDf5rfuqWZmJJpHWJFmPOVeAwY//Z+pOk75Nfe9faK5zs5NjhhijBUxgcDDBBgCA35wHwea117EybJmUmOYB5oUhU2T38AZhYo++TOFtOyOF33vCY0nad5TO+ZJo+KXqR33XnrLEVfI1dKNcDV+ImfpZREgNo+xeyZvwp/+++qOZnhAZg/RRZ/xETKbKBpx5GPzeO7H5iuYN5Uj/63R1JSCJ4M/FrGjuOxVY+lXBQKRpXmIP8fFYt+PFLE730tvq7wXMXNrIO/UchZ1o+elc2SHY4aVI2RS68a1iAoAHuG2ZVLxfIi6t2XxLdXNDeLQjsR2V0I2qO9CzxNJfr+PsCN66mkReEv/m9LWrlC4Xhh03g/iJ1LJFgNKutnNCRUKgcqIQ4Eh2MMvvj60K8GBHmRYgPTGo4tb3WzUIpu0cmE=
